# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChoirMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member_resources.ArrangedPart')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SongPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.ArrangedPart')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.Song')),
            ],
        ),
        migrations.CreateModel(
            name='SongPartResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.ResourceType')),
                ('song_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.SongPart')),
            ],
        ),
        migrations.CreateModel(
            name='SongPartSungBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choir_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.ChoirMember')),
                ('song_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.SongPart')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='songpartresource',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='songpart',
            unique_together=set([('song', 'part')]),
        ),
    ]
