# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPartRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='songpartresource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='songpartresource',
            name='song_part',
        ),
        migrations.RemoveField(
            model_name='songpartresource',
            name='version',
        ),
        migrations.AddField(
            model_name='songpart',
            name='score_filename',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResourceType',
        ),
        migrations.DeleteModel(
            name='SongPartResource',
        ),
        migrations.AddField(
            model_name='songpartrecording',
            name='song_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.SongPart'),
        ),
        migrations.AddField(
            model_name='songpartrecording',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member_resources.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='songpartrecording',
            unique_together=set([('song_part', 'version')]),
        ),
    ]
