# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_resources', '0002_auto_20161110_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songpart',
            name='score_filename',
        ),
        migrations.AddField(
            model_name='songpart',
            name='score',
            field=models.FileField(blank=True, upload_to='scores'),
        ),
        migrations.AlterField(
            model_name='songpartrecording',
            name='filename',
            field=models.FileField(upload_to='recordings'),
        ),
    ]
